name: multisensory
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2019.11.28
  - ffmpeg=4.3.1
  - freetype=2.10.2
  - gmp=6.2.0
  - gnutls=3.6.13
  - lame=3.100
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libiconv=1.16
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - nettle=3.4.1
  - openh264=2.1.1
  - pip=19.3.1
  - python=2.7.18
  - python_abi=2.7
  - readline=8.0
  - setuptools=44.0.0
  - sqlite=3.32.3
  - tk=8.6.10
  - wheel=0.33.6
  - x264=1!152.20180806
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - backports-functools-lru-cache==1.6.1
    - backports-weakref==1.0.post1
    - bleach==1.5.0
    - cycler==0.10.0
    - enum34==1.1.10
    - funcsigs==1.0.2
    - functools32==3.2.3.post2
    - futures==3.3.0
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.31.0
    - h5py==2.10.0
    - html5lib==0.9999999
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - matplotlib==2.2.5
    - mock==3.0.5
    - numpy==1.16.6
    - opencv-python==4.2.0.32
    - opt-einsum==2.3.2
    - pandas==0.24.2
    - pillow==6.2.2
    - protobuf==3.13.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - scipy==1.2.3
    - six==1.15.0
    - subprocess32==3.5.4
    - tensorboard==1.8.0
    - tensorflow==1.8.0
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - werkzeug==1.0.1
    - wrapt==1.12.1

